### ISSUE TITLE
Empty pdf while calling internal api by URL

### ISSUE THREAD

**Issue by justinecomment** [devongovett/node-wkhtmltopdf#131]
Hi there!
i'm facing a big issue and can't find any workaround to make it work.
The setting is quite simple : I have a button which on click i generate a pdf by calling an url that generates the pdf.
I'm trying to make it work by calling the url through my node script but it only generates an empty pdf.
Here's the simplified version just to show how it's supposed to work
The node script :

```
app.post('/', function(req, res) {
    const url = "http://localhost:1234/renderPdf";
    const path = "./src/components/reportPdf.pdf";

    wkhtmltopdf(url, { pageSize: 'letter' })
  .pipe(fs.createWriteStream(path));
    res.end();
});
```

The /renderPdf :

`const RenderPdf = () => { 
    
    return (
        '<h3>`Test`</h3>'
    )
}`

Has anyone encountered this issue? I'm really struggling on it and i've tried almost everything, got all the polyfills that i needed (or seemed to) and still nothing.

Thanks for your kind help!

**Comment by zxlin** [comment]
This is an usage issue. You're calling `res.end` immediately, you don't give `wkhtmltopdf` lib any chance to generate the code, so it ends up being a blank PDF because `res.end` terminates the connection there basically immediately. Remove line and it should work.

**Comment by justinecomment** [comment]
No it's not working even if i remove it :/
