### ISSUE TITLE
Converting local webpage

### ISSUE THREAD

**Issue by kerog** [devongovett/node-wkhtmltopdf#2]
Hi,
Is any way to convert local HTML page to PDF without any web server? Page have linked CSS and some *.png files. I can do this from command line.

**Comment by joaojesusvictor** [comment]
Let me know, for my certainty, does wkhtmltopdf(file://full_path_to_html_file.html) get the whole html page with css and images? Since this page has embedded and not linked image?

Does it work 10 years later?

If yes, how do I embed the images in the html? Based64 on the "src" of the "img" tag?
