### ISSUE TITLE
Post parameters do not send with request

### ISSUE THREAD

**Issue by mdarkis** [devongovett/node-wkhtmltopdf#26]
You currently are allowing for the parameter of --post but not actually using it correctly. You cannot send a post parameter encapsulated in quotations. An example: 

wkhtmltopdf --post 'test hello' 'https://google.com' google.pdf

This will not work as the post param will fail. You must wrap only the value of the post param in quotations like so:

wkhtmltopdf --post test 'hello' 'https://google.com' google.pdf

This will submit correctly. This is also useful when you wish to send JSON strings (like I am sending in my request). I have attached below my solution to your code that will allow for POST params to be sent. However this solution will only allow for one post param currently but I believe that to be another issue with how your code operates. Let me know if you have any questions and I hope this is helpful :).

```
{"post": "json>>>>>hello"}
```
```
if (key !== 'toc' && key !== 'cover' && key !== 'page' && key !== 'post')
      key = key.length === 1 ? '-' + key : '--' + slang.dasherize(key);

if (key == 'post') {
  var postString = '';
  var tempStrArr = val.split('>>>>>');

  for (i = 0; i < tempStrArr.length; i++) {
    if (i == 0)
      postString += '--' + key;

    if (i == 1 && i == tempStrArr.length - 1) {
      postString += "'" + tempStrArr[i] + "'";
    } else if (i == 1 ) {
      postString += "'" + tempStrArr[1];
    } else if (i == tempStrArr.length - 1) {
      postString += " " + tempStrArr[i] + "'";
    } else {
      postString += ' ' + tempStrArr[i];
    }
  }
  args.push(postString);
} else {
  if (val !== false)
    args.push(key);
  if (typeof val !== 'boolean')
    args.push(quote(val));
}
```

**Comment by zxlin** [comment]
@mdarkis see 157bde3 I changed the way that repeatable options are handled.
