### ISSUE TITLE
Getting enoent spawn on windows 7 64bit

### ISSUE THREAD

**Issue by RaniSharim** [devongovett/node-wkhtmltopdf#29]
If I try to use this on my windows machine I keep getting enoent spawn.
I managed to hack around it by changing wkhtmltopdf.command to be the full path, instead of relaying on the path environment variable (ie  wkhtmltopdf.command  = 'C:/wkhtmltopdf/bin/wkhtmltopdf.exe'; )

**Comment by neuston** [comment]
Thank you very much. RaniSharim. I've just encountered the same issue. I might have to waste lots of time to fix the problem without your remainder.
