### ISSUE TITLE
qfont::setpixelsize: pixel size <= 0 (0) aborts unnecessarily

### ISSUE THREAD

**Issue by pbaehr** [devongovett/node-wkhtmltopdf#31]
From what I've gathered this is a warning originating from Qt. It doesn't seem to impact the generation and running wkhtmltopdf from the command prompt it continues and just displays a warning. When I disable the error checking code the PDF generates and comes back fine.

I haven't been able to find a good way to distinguish between errors and warnings from wkhtmltopdf. I've solved it in my fork but not in a way I'm satisfied with:
https://github.com/pbaehr/node-wkhtmltopdf/blob/master/index.js#L65

Not sure if you can think of a better way of selectively deciding whether or not to bail on errors. I didn't open a pull request because a more general approach probably makes more sense. I'm not sure how many other warning conditions are being handled as errors here.

**Comment by novemberalpha** [comment]
First, thanks for making this package. 

I have a team attempting to use it and we are also finding that it crashes node when wkhtmltopdf reports the warning mentioned above to stderr. 

Our short term fix has been to go to line 79 of node_modules/wkhtmltopdf/index.js and comment it out. 

+1 this issue to get it resolved at the package.

**Comment by keithrz** [comment]
We really need an option to specify whether or not errors/warnings logged to stderr cause the entire process to fail.

Maybe 2 options:

* stderrFail: true/false, default true.  If true, call handleError when wkhtmltopdf process writes to stderr.  If false, do nothing unless stderrHandler is defined
* stderrHandler: function to run when wkhtmltopdf process writes to stderr.  Most users would probably pass a function that logs the warning somewhere.  The function could still run before failure if failOnStderr is true.

+1

**Comment by zxlin** [comment]
#58 Pull request merged. You can now suppress warnings with the ignore key in options. See README for usage.
