### ISSUE TITLE
wkhtmltopdf: command not found

### ISSUE THREAD

**Issue by ABeltramo** [devongovett/node-wkhtmltopdf#32]
I installed on my machine the pkg from the main wkhtmltopdf site. If i run the command from terminal it succesfully generate PDF.
The problem is that using your wrapper on node result in this error:

```
Uncaught node.js Error 

Error: /bin/sh: wkhtmltopdf: command not found
    at Socket.<anonymous> (/Users/ale/Downloads/node-webkit-v0.10.5-osx-x64/copia&incolla.app/Contents/Resources/app.nw/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:196:16)
    at Socket.EventEmitter.emit (events.js:104:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Socket.Readable.push (_stream_readable.js:123:10)
    at Pipe.onread (net.js:520:20)
```

Mac OSX 10.10 Yosemite.

**Comment by Dr-Head** [comment]
I'm having the same issue and when I do
```which wkhtmltopdf```
I get the output

```/usr/local/bin/wkhtmltopdf```

**Comment by mauvm** [comment]
The `wkhtmltopdf` command is executed as a [shell command on non-Windows systems][1]. Make sure the `/user/local/bin` directory is in your $PATH variable. Do this by running:

```bash
$ sh
sh-3.2$ which wkhtmltopdf    # Or try:
sh-3.2$ echo $PATH
sh-3.2$ exit
```

[1]: https://github.com/devongovett/node-wkhtmltopdf/blob/master/index.js#L55
[2]: http://fishshell.com/

**Comment by Dr-Head** [comment]
Yeah it's currently in the `/usr/local/bin/wkhtmltopdf` path.

I assume you mean the `usr`(Unix System Resources) path and not `user` Although a `\Users` directory does exist.

**Comment by mauvm** [comment]
Oops, probably muscle memory, but yes I meant `usr`.

What does `/bin/sh -c "which wkhtmltopdf"` give you? If that doesn't work, it is probably a $PATH related problem, else it has something to do with Node (maybe the spawned process).

**Comment by Dr-Head** [comment]
The output I get for the first command is '/usr/local/bin/wkhtmltopdf'

**Comment by denizozger** [comment]
I have the same problem too, same as Dr-Head.

**Comment by Dr-Head** [comment]
What I ended up doing was downloading the dmg directly from wkhtmltopdf and that seemed to do the trick.

http://wkhtmltopdf.org/downloads.html

**Comment by robertmain** [comment]
I'm depending on node-wkhtmltopdf for hackmyresume and it's worth noting that I installed the wkhtmltopdf installation from http://wkhtmltopdf.org/downloads.html. I'm on windows 10 x64 and I'm getting ENOENT from hackmyresume when it tries to use wkhtmltopdf. It turns out that this is because running `which wkhtmltopdf` in the terminal just returns nothing. Someone else above said that this indicates that there is something wrong with your install of wkhtmltopdf. Could someone weigh in here?

**Comment by thokari** [comment]
@robertmain Not sure about Cygwin/Git shell that you are using. The 'which' command is just meant to show you the full path to a command, however it is Linux, and if I am correct, that there is at least a configuration option to "import" your Windows PATH into your Cygwin shell (there is also a warning about it to only use it when you know what you are doing, which I dont ;)
This might help you http://stackoverflow.com/questions/304319/is-there-an-equivalent-of-which-on-the-windows-command-line
When you run Node on Windows, it will certainly use the Windows PATH, not the Cygwin one.

**Comment by apowers313** [comment]
Any thoughts about using [wkhtmltopdf-installer](https://www.npmjs.com/package/wkhtmltopdf-installer) to automatically pick up the right path and / or install wkhtmltopdf if needed?

**Comment by zxlin** [comment]
@apowers313  [wkhtmltopdf-installer](https://www.npmjs.com/package/wkhtmltopdf-installer) looks interesting, but the README seems to indicate that it only grabs the binary from Linux (Debian Wheezy)

I'd love to add this if it supports more than just Debian based systems.

**Comment by apowers313** [comment]
The README sure doesn't convey what it does very well -- I've verified that it works on OSX and the code makes it look like it works on Windows as well:
https://github.com/pofider/node-wkhtmltopdf-installer/blob/master/lib/index.js

**Comment by zxlin** [comment]
If anyone can verify this works on Windows and maybe the Hat systems too, that'd be great. 

Otherwise I'll check it out when I have some free time.

**Comment by ArunMichaelDsouza** [comment]
Installing wkhtmltopdf from this link - http://wkhtmltopdf.org/downloads.html#stable solved the issue for me.

**Comment by Hakog** [comment]
Maybe a bit off-topic.

Sometimes i run wkhtmltopdf on a environment where wkhtmltopdf is not available. When this happens an uncaught error occurs and my App is crashed.
```
events.js:154
throw er; // Unhandled 'error' event
```

I've noticed that the reason for this to happen is the pipe to cat. Without this the child process exits with an error code which can be handled by the application. But an uncaught error on the other hand gives me the creeps. 

Two questions:
- Why is the pipe to cat necessary ?
- How come this causes an uncaught exception ?

My environment:
node: 5.11.1
wkhtmltopdf: 0.3.1

Thanks for the great work on this module!

**Comment by zxlin** [comment]
@Hakog The pipe is there because for some reason wkhtmltopdf simply crashes due to some piping issues. I've tried removing it and but I'm not sure what's causing wkhtmltopdf to crash. That code was written by the original maintainer. 

Someone suggested that we go with cpp bindings instead (#82). I may look into that in the future and that would resolve all of the issues presented here.

**Comment by Hakog** [comment]
@zxlin Thanks! I noticed the crash without the pipe. When i have some time to spare i will look into the cpp binding.

I will make a PR later this day with a fix to solve the issue where the entire app crashes when the shell command is not available or fails for some other reason.

**Comment by caiyongmin** [comment]
i install wkhtmltopdf both on project and global. but when i run `which wkhtmltopdf`, i get below message:

```bash
which wkhtmltopdf
wkhtmltopdf not found
```

any other guys had see that ?

**Comment by PyroSA** [comment]
@caiyongmin - please refer to the reader.
This is just a wrapper, you need to install the wkhtmltopdf command line tool yourself.

**Comment by sydkaz** [comment]
I am getting the same error "sh: wkhtmltopdf: command not found" when trying to generate PDF using exec() in PHP  however the same "wkhtmltopdf" works perfectly fine from SSH I am using CentOS7 on my server, all other SSH commands works fine from exec() except for "wkhtmltopdf" one.

Any thoughts why would that be happening?

**Comment by mauvm** [comment]
Run `which wkhtmltopdf` (shows something like /usr/local/bin/wkhtmltopdf)
and check if the path to the executable is in your PATH variable for PHP.
See this thread:
http://stackoverflow.com/questions/6901583/adding-to-the-path-environment-variable-in-a-php-script.
Good luck!

**Comment by robertmain** [comment]
Not to be funny but what does PHP have to do with anything?

**Comment by sydkaz** [comment]
Mauvm thanks for responding, I managed to fix that issue by providing the binary path in the constructor as an argument

$pdf = new  Image(array(
    'binary' => '/usr/local/bin/wkhtmltoimage',
    ));

**Comment by ChampIsMe** [comment]
is this library meant to be used in some production code hosted remotely?? Since all the path I see posted here are about locations in the local computer. for example, how do I use this in Google app engine?
