### ISSUE TITLE
Support src=//

### ISSUE THREAD

**Issue by kenorb** [devongovett/node-wkhtmltopdf#43]
I've remote URL such as [this](http://www.scribd.com/doc/15049545/Saxo-Trader-2-Walk-Through) one.

However when I'm downloading, it's showing the following warnings:

    Loading pages (1/6)
    Warning: Failed to load file://cdn.optimizely.com/js/653710485.js (ignore)
    Warning: Failed to load file://pagead2.googlesyndication.com/pagead/js/google_top_exp.js (ignore)
    Warning: Failed to load file://www.google-analytics.com/analytics.js (ignore)
    Warning: Failed to load file:///images/filetypes/pdf.png (ignore)
    Warning: Failed to load file:///images/filetypes/txt.png (ignore)
    Warning: Failed to load file://www.googletagservices.com/tag/js/gpt.js (ignore)
    Warning: Failed to load file://connect.facebook.net/en_US/sdk.js (ignore)

The files in the source are like:

    <script src="//cdn.optimizely.com/js/653710485.js">
    <script src="//pagead2.googlesyndication.com/pagead/js/google_top_exp.js">

Is there any way that `wkhtmltopdf` can assume automatically that these files are http by default (the same protocol as it's used during downloading)?

**Comment by devongovett** [comment]
Please report to https://github.com/wkhtmltopdf/wkhtmltopdf. This has nothing to do with the node wrapper.

**Comment by kenorb** [comment]
Sorry, I missed that. Follow up: [Support for src=/ and src=// #2359](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2359)
