### ISSUE TITLE
General Options in Meteor.js

### ISSUE THREAD

**Issue by samurai-jack** [devongovett/node-wkhtmltopdf#44]
I use node-wkhtmltopdf in meteor.js
I have a problem with General Options

Here is ma code:
  this.route('pdfFile', {
      where: 'server',
      path: '/test.pdf',

      action: function() {

          // This action function allows you to edit the response buffer.

          // create some http buffers for your pdf file
          var headers = {
              'Content-type': 'application/pdf',
              'Content-Disposition': "attachment; filename=test.pdf"
          };

          // Add the headers to the response buffer
          this.response.writeHead(200, headers);

          // Load the wkhtmltopdf module.
          // Notice we are using Meteor.npmRequire here, available trough the meteorhacks:npm module.
          var wk = Meteor.npmRequire('wkhtmltopdf');

          // Render the html response of 'http://www.google.com' to the response buffer.
          var r = wk("http://10.11.12.13:3000/repertorium/insert", { pageSize: 'letter' }).pipe(this.response);
      }
  });
})

I use pageSize: 'letter' from General Option it`s works but i don`t know how to add another General Option exp. "--user-style-sheet"

THX

**Comment by zxlin** [comment]
pass it in the options param
```
options = {
  userStyleSheet : 'value'
}
```
