### ISSUE TITLE
Error handling preemptively calls callback

### ISSUE THREAD

**Issue by MatthewRayfield** [devongovett/node-wkhtmltopdf#46]
The current method for handling errors calls the callback (and kills the child process) on the first sight of an error, or even a warning.

This is an issue if it's a harmless warning and it would be better to let the child process run it's course.

This was an issue for us when we got the following warning:
> QSslSocket: cannot resolve SSLv2_client_method

This warning did not prevent the creation of a PDF, but because node-wkhtmltopdf calls the callback when it sees an error, it led our next step in code to run before the PDF was saved.

I've made a fix and will submit it as a pull request, but you may have a different idea about how to solve this issue.

Thanks!

**Comment by nicluo** [comment]
+1. 

My error though was the same as #31, I think some of the pending pull requests are addressing this issue.

I had this forked and manually patched with #48 so that I can use the repo as an npm dependency for now. This fix I'm using is temporary at best.

**Comment by kabitakis** [comment]
:+1:

**Comment by tepez** [comment]
+1

This warning should not fail the process: `libpng warning: Incorrect sBIT chunk length`

**Comment by mnort9** [comment]
+1

**Comment by zxlin** [comment]
See latest for options.ignore to suppress warnings.
