### ISSUE TITLE
--xsl-style-sheet option not working.

### ISSUE THREAD

**Issue by jlews** [devongovett/node-wkhtmltopdf#59]
I'm specifying the stylesheet for a table of contents using the following as my options argument:
```
var options = {
  toc: true,
  xslStyleSheet: "./toc_styles.xsl"
};
```
This generates the following error from the `wkhtmltopdf` command:
```
Error: --xsl-style-sheet specified in incorrect location
```
It seems that the `--xsl-style-sheet` argument has to be **after** the `toc` argument in order to work.

**Comment by zxlin** [comment]
Your #60 PR has been merged
