### ISSUE TITLE
Repository status and activity

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [devongovett/node-wkhtmltopdf#61]
Hi @devongovett,

The company I work for @Woorank, uses the very useful `node-wkhtmltopdf` NPM package and we were wondering about the status of this repository.

We needed to fix the issue where QTWebkit warning were considered like errors and made the process exit with a code 1. The following pull request: #58, made by user @zxlin fixes this issue but hasn't been merged or commented on since it was created a little more than a month ago.

If you don't have time to work on the project anymore would you consider transferring the project to us?

We actively use it in our infrastructure so we're also interested in extending and supporting it.

I hope you'll consider this request!
Have a nice day,

Mickael

**Comment by zxlin** [comment]
I'd be willing to maintain the repository as well. I use this package regularly in a production project.

**Comment by jeff-h** [comment]
Sorry to "me-too" on this, but I need #58 merged as well, for this to work for me. It would be great if you'd be willing to open up the project to these guys if they're willing maintainers.

**Comment by NachtRitter** [comment]
+1
I'd like to know status and future plans for this package too. In my company we widely use this package, so it's good to know what to do. Is it time to find new package or to hope for supporting and developing in future this for one.
@devongovett, please answer. Thanks a lot.

**Comment by parisambush** [comment]
+ 1
I've also been eagerly awaiting an update on this project. I want to use this for a dynamic HTML to PDF generator I'm making but am running into the same issue as the folks about and don't want to really implement something too hacky to fix. This is a great wrapper for a very useful tool and hope there will be an update soon.

**Comment by devongovett** [comment]
@zxlin @Mickael-van-der-Beek I've added you both as collaborators on github. Also added @zxlin as an owner on npm. I'll add @Mickael-van-der-Beek as well, but I don't have your npm username.

Sorry for the delay. I'm super busy these days. Thanks for taking up maintenance of this project.
