### ISSUE TITLE
Pass x-access-token HTTP Header

### ISSUE THREAD

**Issue by intensite** [devongovett/node-wkhtmltopdf#63]
The page I would like to render to pdf is on a server that expects a JSON Web Token in the request HTTP header : x-access-token.

Is it possible to pass a x-access-token HTTP Header as an option to wkhtmltopdf along with the url?

I have experimented with the command line wkhtmltopdf using the --custom-header and --custom-header-propagation parameters and it works fine. However, I am not able (or don't know how) to pass these to the wkhtmltopdf node wrapper. 

Stephen..

**Comment by zxlin** [comment]
I believe you can pass into options:
```javascript
{
  'custom-header' : 'value',
  'custom-header-propagation' : 'value'
}
```
the options hash just takes in key:value input and adds single dash or double dash as necessary

**Comment by zxlin** [comment]
Sorry that I didn't look more into this issue earlier, 157bde3 should fix repeatable options. 

You pass something like the following option into wkhtmltopdf
```JavaScript
{
  customHeader : ['name', 'value']
}
```
