### ISSUE TITLE
Client-side option?

### ISSUE THREAD

**Issue by atdiff** [devongovett/node-wkhtmltopdf#70]
Is there a client-side version of this or someway to run it in browser for other users without a command line?

**Comment by zxlin** [comment]
Unfortunately, this is a server side tool. You should checkout [pdfkit](https://github.com/devongovett/pdfkit) if you want to do in browser PDF rendering. 

pdfkit works a little different and cannot do HTML to PDF generation, instead it's a HTML5 canvas-like API to add elements into the PDF file.
