### ISSUE TITLE
wkhtmltopdf is licensed GPLv3, but this is licensed MIT. how?

### ISSUE THREAD

**Issue by tjwebb** [devongovett/node-wkhtmltopdf#75]
The underlying [wkhtmltopdf](http://wkhtmltopdf.org/) tool is licensed GPLv3.

From https://en.wikipedia.org/wiki/MIT_License:

> The MIT license is also compatible with many copyleft licenses, such as the GPL; MIT licensed software can be integrated into GPL software, but not the other way around.[4]

**Comment by GloverDonovan** [comment]
wkhtmltopdf is licensed under the **Lesser** General Public License (LGPLv3), not GPLv3. There shouldn't be a problem with licensing this software under MIT as the binary is not modified.

> LGPL — stands for Lesser GPL (used to mean Library GPL). The significant difference with GPL is, that **it doesn't impose the license on software using the library**. Only if you'd modify the library or directly include parts of the code in your software, then your code would have to be LGPL. 

(Emphasis mine)
Source: http://programmers.stackexchange.com/a/141848/72104
