### ISSUE TITLE
Stream accessed using callback does not work

### ISSUE THREAD

**Issue by DbCrWk** [devongovett/node-wkhtmltopdf#77]
The stream accessed in this calling pattern:
```
wkhtmltopdf('http://google.com/', { pageSize: 'letter' }, function (err, stream) {
  // do whatever with the stream
});
```
does not work. Moreover, when logging the `stream` to the console, the stream also has the `readable` prop as false.

**Comment by zxlin** [comment]
@DbCrWk should be fixed in 0.3.3
