### ISSUE TITLE
css IS NOT APPLYING

### ISSUE THREAD

**Issue by awesomehimanshu** [devongovett/node-wkhtmltopdf#78]
CSS IS NOT APPLYING 

wkhtmltopdf('https://jaimegris.wordpress.com/2015/03/03/how-to-install-wkhtmltopdf-in-centos-6-5/', { pageSize: 'letter' })
  .pipe(fs.createWriteStream('out.pdf'))

[out.pdf](https://github.com/devongovett/node-wkhtmltopdf/files/359300/out.pdf)

**Comment by nronnei** [comment]
Did you ever figure this out?

**Comment by rr-ricky** [comment]
hey what happened man
