### ISSUE TITLE
I need callback

### ISSUE THREAD

**Issue by awesomehimanshu** [devongovett/node-wkhtmltopdf#79]
I need callback when it successfully create pdf. In this code there is no callback its take time to generate pdf . so i want when it done with all the file create then is send response
wkhtmltopdf(str)
.pipe(fs.createWriteStream(newPath+"/public/"+fileName));

**Comment by zxlin** [comment]
hey @awesomehimanshu, It sounds like you want this, but I'm not sure if I understand your needs properly:
```
wkhtmltopdf('http://google.com/', { pageSize: 'letter' }, function (err, stream) {
  // note the stream arg in the callback. 
});
```
Please elaborate if this is not what you want.

**Comment by awesomehimanshu** [comment]
i have solved it thanks

**Comment by awesomehimanshu** [comment]
wkhtmltopdf(str,{ pageSize: 'letter' },{output: newPath+"/tmp/"+fileName},function(err,stream){

});


saying   "TypeError: callback is not a function",

 I know i have send one extra argument but i want to do so how can i do it

**Comment by awesomehimanshu** [comment]
plz i need it . If you have any solution tell me

**Comment by zxlin** [comment]
Try this:
```JavaScript
wkhtmltopdf(str, { pageSize: 'letter', output: newPath + '/tmp/' + fileName }, function(err,stream) {
  // note that the options hash can contain multiple values. 
});
```

**Comment by awesomehimanshu** [comment]
thanks it works
