### ISSUE TITLE
how can i set margin?

### ISSUE THREAD

**Issue by awesomehimanshu** [devongovett/node-wkhtmltopdf#81]
I am creating pdf from html and i am getting magin in all side of pdf
![screenshot from 2016-07-18 12 31 41](https://cloud.githubusercontent.com/assets/16804408/16907743/9ee7f084-4ce3-11e6-8984-8d924c769b5f.png)

how can i remove it  . I am using this code to generate pdf 
 wkhtmltopdf(str,{output: newPath+"/tmp/"+fileName},function(err,stream){  });

**Comment by zxlin** [comment]
Hey, wkhtmltopdf usage information can be found here: http://wkhtmltopdf.org/usage/wkhtmltopdf.txt

**Comment by awesomehimanshu** [comment]
i know but how to use margin 0 in all side in this query can you tell me .

**Comment by awesomehimanshu** [comment]
i solve it like this 		 wkhtmltopdf(str,{ "margin-top":0,"margin-bottom":0,"margin-left":0,"margin-right":0,pageSize: 'A4', output: newPath+"/tmp/"+fileName},function(err,stream){
