### ISSUE TITLE
wkhtmltopdf "Error: Exit with code 1 due to network error: HostNotFoundError"

### ISSUE THREAD

**Issue by Krishna0612** [devongovett/node-wkhtmltopdf#84]
Hi,

I am trying to convert an html to pdf using wkhtmltopdf. 
My wkhtmltopdf version is wkhtmltopdf 0.12.3.2 (with patched qt)
My command is : `wkhtmltopdf http://google.com file://C:/Users/`
I am getting error as : 
```
Error: Failed loading page http://google.com (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError
```

Kindly help me out to remove this error.

**Comment by zxlin** [comment]
For the command line tool usage please refer to https://github.com/wkhtmltopdf/wkhtmltopdf
