### ISSUE TITLE
Progress indicators

### ISSUE THREAD

**Issue by samcorcos** [devongovett/node-wkhtmltopdf#88]
Is there a way to show progress indicators? My compilation takes quite a long time and it's hard to know if it's hung up on something. 

I realize the core of this is written in C, so I probably won't be able to contribute a PR... But if there's something that can be done on the JS side of things, I'm happy to help.

**Comment by samcorcos** [comment]
Actually, I think part of the documentation solved my problem. It's not quite a progress indicator, but it's close:

```js
  wkhtmltopdf(styledHTML, {
    debugJavascript: true,
    debug: true
   })
   .pipe(fs.createWriteStream('out.pdf'))
```

**Comment by samcorcos** [comment]
Also, I noticed some strange behavior. When I do not include `debug: true`, the process often gets stuck for >30 minutes, but when it is included, it works 100% of the time within a reasonable duration. No idea why that would be the case... Happy to investigate if anyone else runs into this as well.

**Comment by interactivesites** [comment]
Hi Sam -- have you had any more insights or success with this issue?
thanks,
Marco
