### ISSUE TITLE
Callback with stream isn't working, creates blank pdfs

### ISSUE THREAD

**Issue by jpike88** [devongovett/node-wkhtmltopdf#91]
` wkhtmltopdf("TEST", {}, function(err, stream) {
                            
                        var data = '';
                        stream.on('data', function(chunk) {
                            data+=chunk;
                        });
                        
                        stream.on('end', function() {

                            fs.writeFileSync('./test', data);
                            fs.writeFileSync('./test2.pdf', Buffer(data, 'binary'));
                            fs.writeFileSync('./test3.pdf', Buffer(data, 'utf8'));

                        })

                    });`

**Comment by zxlin** [comment]
What's the error?

**Comment by jpike88** [comment]
all the PDFs are blank

[test.pdf](https://github.com/devongovett/node-wkhtmltopdf/files/660362/test.pdf)
[test2.pdf](https://github.com/devongovett/node-wkhtmltopdf/files/660363/test2.pdf)
[test3.pdf](https://github.com/devongovett/node-wkhtmltopdf/files/660364/test3.pdf)

**Comment by jpike88** [comment]
Found the problem:

`var isUrl = /^(https?|file):\/\//.test(input);
  args.push(isUrl ? quote(input) : '-');    // stdin if HTML given directly
  args.push(output ? quote(output) : '-');  // stdout if no output file
`

There's no room to pipe in an HTML string in the code

**Comment by jpike88** [comment]
Actually tested it now with actual URLs, still making blank pdfs.

**Comment by jpike88** [comment]
[index.js.zip](https://github.com/devongovett/node-wkhtmltopdf/files/660464/index.js.zip)

**Comment by zxlin** [comment]
Sorry @jpike88, I've been traveling this month and haven't had time to look at this too much. May I ask what version of node are you running this with? I think it has something to do with the node stream implementation.

**Comment by zxlin** [comment]
Furthermore, I think the callback should really return a Buffer of the final data instead of a Stream because the callback is only called when wkhtmltopdf exits, at which point, a Stream seems strange to return.

**Comment by jpike88** [comment]
Does that index.js run ok for you?

**Comment by zxlin** [comment]
I'm traveling and don't have my normal dev box with me, so I haven't been able to. I'd like to know the node version you're using still so I can try to repro later. 






On Wed, Jan 18, 2017 at 8:26 AM +0800, "jpike88" <notifications@github.com> wrote:












Does that index.js run ok for you?

**Comment by jpike88** [comment]
6.9.2

**Comment by jpike88** [comment]
I'll close this and subscribe to the other issue... no chance of this being sorted till debug is easy to do

**Comment by intensite** [comment]
Just wondering if this issue was resolved since then?

I am trying to email the stream resulting PDF but the result is always a few blank pages.
I can attach the resulting 41Kb pdf file if required.
Regards.

Stephen..
