### ISSUE TITLE
Default parameter --quiet prevents debugging

### ISSUE THREAD

**Issue by misantronic** [devongovett/node-wkhtmltopdf#92]
Per default, the parameter `--quiet` is passed to `wkhtmltopdf`

(see: index.js:51)
`var args = [wkhtmltopdf.command, '--quiet'];`

The quiet-options prevents debugging and thus displaying javascript-output.
Is there a way to disable `quiet` apart from just removing it from the file?

**Comment by zxlin** [comment]
See #93 for follow up
