### ISSUE TITLE
Pass debug-parameter as a function

### ISSUE THREAD

**Issue by misantronic** [devongovett/node-wkhtmltopdf#93]
I find it very useful to retrieve all the debugging output in my app when generating pdfs.
To do this it might be great to pass `debug` as a function.

Here is my proposal solving this:
https://github.com/devongovett/node-wkhtmltopdf/compare/master...misantronic:master

**Comment by zxlin** [comment]
@misantronic I'm traveling this month so I don't have my normal dev box with me. Can you give 59783b2f4f05a5b60133580eaa3e4f4ff40ef9f0 a spin and let me know?

**Comment by misantronic** [comment]
Looks perfect! Thanks a lot for your fast response. 👍

**Comment by zxlin** [comment]
Great, will bump npm after I resolve #91

**Comment by misantronic** [comment]
You applied the statement at the wrong. I commented on your commit.

**Comment by misantronic** [comment]
Just wanted to check back on you. Will you still correct your mistake adding the code snippet to the wrong line?
